// A deliberately small renderer for this repository's trusted Markdown documents.
import {readFile,writeFile,copyFile} from 'node:fs/promises';
import {resolve} from 'node:path';
const root=resolve(import.meta.dirname,'..');
const escape=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
function inline(text){return escape(text).replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/\[([^\]]+)\]\(([^)]+)\)/g,(_,label,url)=>`<a href="${url.replace('../dist/','./').replace('docs/model.md','#model').replace('docs/data.md','#data').replace('docs/roadmap.md','#roadmap').replace('docs/target-test.md','#target-test').replace(/^genesis\.md$/,'#genesis')}">${label}</a>`);}
function markdown(text){
 const lines=text.split(/\r?\n/),out=[];let paragraph=[],list=null;
 const flush=()=>{if(paragraph.length){out.push('<p>'+inline(paragraph.join(' '))+'</p>');paragraph=[];}if(list){out.push('</'+list+'>');list=null;}};
 for(let i=0;i<lines.length;i++){
  const line=lines[i];
  if(line.startsWith('```')){flush();const code=[];for(i++;i<lines.length&&!lines[i].startsWith('```');i++)code.push(lines[i]);out.push('<pre><code>'+escape(code.join('\n'))+'</code></pre>');continue;}
  const heading=line.match(/^(#{1,6})\s+(.*)/);if(heading){flush();if(heading[1].length===1)continue;const level=Math.min(4,heading[1].length+1);out.push(`<h${level}>${inline(heading[2])}</h${level}>`);continue;}
  if(line.startsWith('|')&&lines[i+1]?.match(/^\|[\s:|\-]+\|$/)){flush();const cells=row=>row.split('|').slice(1,-1).map(x=>x.trim());out.push('<div class="table-wrap"><table><thead><tr>'+cells(line).map(x=>'<th>'+inline(x)+'</th>').join('')+'</tr></thead><tbody>');i+=2;for(;i<lines.length&&lines[i].startsWith('|');i++)out.push('<tr>'+cells(lines[i]).map(x=>'<td>'+inline(x)+'</td>').join('')+'</tr>');i--;out.push('</tbody></table></div>');continue;}
  const item=line.match(/^(?:([-*])|(\d+)\.)\s+(.*)/);if(item){if(paragraph.length){out.push('<p>'+inline(paragraph.join(' '))+'</p>');paragraph=[];}const type=item[2]?'ol':'ul';if(list!==type){if(list)out.push('</'+list+'>');out.push('<'+type+'>');list=type;}out.push('<li>'+inline(item[3])+'</li>');continue;}
  if(!line.trim()){flush();continue;}if(list){out.push('</'+list+'>');list=null;}paragraph.push(line.trim());
 }flush();return out.join('\n');
}
const index=await readFile(resolve(root,'dist/index.html'),'utf8');
let header=index.match(/<header[\s\S]*?<\/header>/)[0];header=header.replace('class="current" href="./" aria-current="page"','href="./"').replace('href="./docs.html"','class="current" href="./docs.html" aria-current="page"');
const parts=await Promise.all(['runtime','target-test','genesis','model','data','roadmap'].map(async id=>({id:id==='runtime'?'live':id,html:markdown(await readFile(resolve(root,'docs/'+id+'.md'),'utf8'))})));
const titles={live:'Shared browser controller','target-test':'Browser-local target test',genesis:'Token launch record',model:'Model specification',data:'Data provenance',roadmap:'Research and development plan'};
const content=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#0b2029"><title>Methods & token launch record — Zebrafish Neural</title><meta name="description" content="Zebrafish Neural model equations, data provenance and the confirmed operator-launched ZNEURO token record."><meta name="twitter:site" content="@zebrafishneural"><link rel="canonical" href="https://zebraneural.com/docs.html"><link rel="icon" href="./assets/zebrafish-neural.png" type="image/png"><link rel="stylesheet" href="./style.css"></head><body>${header}
<main><div class="docs-layout"><nav class="docs-nav" aria-label="Methods navigation"><a href="#overview">Overview</a><a href="#live">Live controller</a><a href="#target-test">Target test</a><a href="#experiment">Laboratory</a><a href="#genesis">Token launch record</a><a href="#model">Model specification</a><a href="#data">Data provenance</a><a href="#roadmap">Development plan</a><a href="./">← Live view</a></nav><article class="docs-content">
<section id="overview"><div class="doc-kicker">Zebrafish Neural / METHODS AND DATA</div><h1>The model, its methods<br>and the token launch record.</h1><p>Zebrafish Neural connects real browser screenshots to an eight-state model and applies its motor output to the cursor. The shared experiment continues on Wikipedia. The homepage also offers a <a href="#target-test">browser-local target test</a> with synthetic visual input, scored trials and JSON export; each viewer runs a separate session with the same model equations. A separate laboratory provides further controlled stimuli. The operator launched $ZNEURO on Pons on 11 September 2026. <a href="#genesis">The launch record</a> identifies its contract and confirmed transaction. The neural controller did not create or sign the token launch.</p><div class="provenance-grid"><div><h3>Simulated dynamics</h3><p>Eight continuous population states driven by browser-image contrast in the shared run, or synthetic stimuli in the target test and laboratory. The Wikipedia controller and browser-local tests use hand-set parameters. A separate persistent learner adjusts six gains against synthetic target outcomes. Neither model has been fitted to biological activity.</p></div><div><h3>Measured geometry</h3><p>71,721 ZAPBench cell centroids. These positions have no assigned model activity, regional labels or connectivity in this release.</p></div></div></section>
<section id="experiment"><h2>Controlled laboratory sessions</h2><ol><li>Open the <a href="./laboratory.html">laboratory</a>. The controller starts automatically with a moving visual target.</li><li>Compare the retinal image, model states, trajectory and motor time series. The model continues beyond 60 seconds.</li><li>Pause to change stimulus or contrast, then Resume. Restart clears state and recording; a running session continues and a paused session stays paused.</li><li>Export JSON or CSV at any time. Exports retain only the latest 60 model seconds, with original session timestamps.</li><li>Use Population model to inspect simulated activity, or ZAPBench anatomy to examine measured cell positions independently.</li></ol><p>The session suspends when the tab is hidden and resumes when visible unless manually paused. Closing or reloading the laboratory ends that local session. This does not affect the shared live controller. Continuous execution does not imply continuous movement: no stimulus produces no activity, and the looming shadow is a single presentation.</p><p>Drag the brain view or use arrow keys to rotate. The mouse wheel and +/− keys control zoom. Data stay in browser memory until exported.</p></section>
${parts.map(p=>`<section id="${p.id}"><h2>${titles[p.id]}</h2>${p.html}</section>`).join('\n')}
</article></div><footer class="lab-footer"><div><p class="footer-brand">Zebrafish Neural / $ZNEURO</p><p>Computational sensorimotor research prototype.</p></div><a href="https://x.com/zebrafishneural" target="_blank" rel="noopener noreferrer">@zebrafishneural ↗</a><a href="./">Return to the live view ↗</a></footer></main></body></html>`;
await writeFile(resolve(root,'dist/docs.html'),content);
await copyFile(resolve(root,'NOTICE'),resolve(root,'dist/NOTICE'));
console.log('Generated English methods page from the repository documentation.');
